# Generated by Django 5.0.4 on 2024-05-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_booking_pet_alter_booking_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Ongoing', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.CharField(choices=[('Hair Grooming', 'Hair Grooming'), ('Bath and Dry', 'Bath and Dry'), ('Pet Hotel', 'Pet Hotel'), ('Pet Daycare', 'Pet Daycare')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
