# Generated by Django 5.0.4 on 2024-05-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_booking_status_alter_booking_service_alter_pet_breed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='pet',
        ),
        migrations.AddField(
            model_name='booking',
            name='pet',
            field=models.ManyToManyField(to='main.pet'),
        ),
    ]
