# Generated by Django 5.0.4 on 2024-05-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_booking_checkin_booking_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
