# Generated by Django 5.0.4 on 2024-05-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_pet_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
