# Generated by Django 5.0.4 on 2024-05-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_pet_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile.jpg', null=True, upload_to=''),
        ),
    ]
