# Generated by Django 5.0.4 on 2024-05-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_room_booking_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout',
            field=models.DateField(blank=True, null=True),
        ),
    ]
