# Generated by Django 5.0.4 on 2024-05-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_booking_checkin_alter_booking_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(blank=True, choices=[('09:00', '9:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('14:00', '2:00'), ('15:00', '3:00'), ('16:00', '4:00'), ('17:00', '5:00')], max_length=5, null=True),
        ),
    ]
